### ISSUE TITLE
"out.width.px" argument is of length zero

### ISSUE THREAD

**Issue by bounlu** [yihui/knitr#1899] opened 2020-09-23 18:03 UTC
I recently upgraded from R 3.6.3 to 4.0.2 and got into this.

I run `regionReport` with simplest way which is based on `rmarkdown` which uses `knitr`, and I post this here as I believe this arises from `knitr`, apologies if otherwise.

`DESeq2Report(dds, project = project, intgroup = "sampleName", res = dds_res, output = label, outdir = out_dir)`

I get the error:
```
Quitting from lines 34-38 (2040_genes_report.Rmd) 
Error in if (is.na(options$out.width.px)) options$out.width.px = options$fig.width *  : 
  argument is of length zero

Execution halted
```

Lines 34-38 are:
````
```{r docSetup, bootstrap.show.code = FALSE, dev = device, bootstrap.show.message=FALSE}
## knitrBoostrap and device chunk options
library('knitr')
opts_chunk$set(bootstrap.show.code = FALSE, dev = device, crop = NULL)
if(!outputIsHTML) opts_chunk$set(bootstrap.show.code = FALSE, dev = device, echo = FALSE)
```
````

I tried to comment out those lines and adding options such as `out.width`, `fig.width`, `dpi`, none worked, still got the same error for the following lines.

I installed `knitr v1.30`, using R-devel with the most updated packages.

I have seen a related bug was [fixed](https://github.com/yihui/knitr/releases/tag/v1.30) in the latest version, and I notice mine is due to the same options:

> The internal function fix_options() should be called after option hooks are executed

So wondering how to fix this.

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue:
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('knitr')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/knitr')`.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by grimbough** [comment] 2020-09-23 20:09
Some initial triaging suggests this issue is affecting the `BiocStyle` package which I think `regionReport` uses for formatting.  It's currently stopping about 700 packages from building, so we'll try and get a fix ASAP.

**Comment by bounlu** [comment] 2020-09-23 23:06
Ohh yes, I forgot to mention that I also went into `BiocStyle` code to figure out the problem. Good to see that I'm not alone. 👍🏼

**Comment by grimbough** [comment] 2020-09-24 21:44
This should now be fixed in BiocStyle v2.16.1 & v2.17.1 - it'll propagate through the Bioconductor build system in the next day or so.

**Comment by atusy** [comment] 2020-09-26 15:52
@bounlu 

What package provides `regionReport`?
Would you provide a reproducible example following the issue guide you promised? Your report seems to be based on your live project, which is huge.
I'd appreciate if you could make a reproducible example as small as possible.

**Comment by bounlu** [comment] 2020-09-26 16:45
Hi @atusy 

[`regionReport`](https://www.bioconductor.org/packages/release/bioc/html/regionReport.html) is the R package itself.
The issue is caused by `BiocStyle` which is used by `regionReport`, and fixed when I downgraded to `knitr v1.29`.

The minimal example to reproduce the error would be running the main function of `regionReport` with any `dds` object from `DESeq2` having **_`knitr v1.30`_** installed as below:

```
library(DESeq2)
library(regionReport)

counts_table = data.frame(s1 = sample(100), s2 = sample(100), s3 = sample(100))
rownames(counts_table) = paste0("gene", seq(100))
samples_anno = data.frame(sample_name = c("s1", "s2", "s3"), sample_group = as.factor(c("group1", "group1", "group2")))

dds = DESeqDataSetFromMatrix(countData = counts_table, colData = samples_anno, design = ~ sample_group)
dds = DESeq(dds)
dds_res = results(dds, contrast = c("sample_group", "group1", "group2"))
DESeq2Report(dds, intgroup = "sample_name", res = dds_res)
```

**Comment by atusy** [comment] 2020-09-27 12:02
@bounlu I cannot reproduce the error. It works fine.

BTW, your example also requires **pheatmap** package.

**Comment by grimbough** [comment] 2020-09-27 12:46
As mentioned above, this problem was down to an issue in the **BiocStyle** package that **regionReport** uses to style it's output.  The changes in **knitr** 1.30 swapping `knitr:::fix_options()` to after the hooks have been run introduced an error there, but it's already been patched.

**Comment by bounlu** [comment] 2020-09-27 12:47
@atusy 

You cannot reproduce because `BiocStyle` has been updated and fixed this issue.
I notice that this issue occurs in specific combination of `knitr v1.30` and  `BiocStyle 2.17.0`.

**Comment by atusy** [comment] 2020-09-27 12:59
@grimbough @bounlu Ah ha! I was missing the point. Thanks a lot.

Since things are going well now, can we close this issue?

**Comment by cderv** [comment] 2020-09-27 13:32
Thanks everyone !

**Closed by cderv** 2020-09-27 13:32 UTC
