### ISSUE TITLE
knitr interferes with utils::capture.output() 

### ISSUE THREAD

**Issue by JohnMount** [yihui/knitr#1437] opened 2017-09-29 15:45 UTC
`knitr` appears to interfere with utils::capture.output().

Expected behavior: a `knitr` run of a `R-mardown` document containing the code below works as in the R console, printing nothing nothing during the msg assignment and then storing the message "hi" into the msg variable.

Observed behavior (indicated below): the "hi" is instead printed early and the msg variable receives an empty string.

Code:

```{r}
packageVersion("knitr")
msg <- utils::capture.output(
  {
    message("hi")
  },
  type='message')
print(paste('msg is:', msg))
```

Result:

-------------

``` r
packageVersion("knitr")
```

    ## [1] '1.17'

``` r
msg <- utils::capture.output(
  {
    message("hi")
  },
  type='message')
```

    ## hi

``` r
print(paste('msg is:', msg))
```

    ## [1] "msg is: "

-------------

Input `q.Rmd.txt` and result `q.md.txt` are attached to this issue.

[q.md.txt](https://github.com/yihui/knitr/files/1344917/q.md.txt)
[q.Rmd.txt](https://github.com/yihui/knitr/files/1344918/q.Rmd.txt)

**Comment by yihui** [comment] 2017-09-30 02:08
Duplicate of rstudio/rmarkdown#1150

**Closed** 2017-09-30 02:08 UTC
