### ISSUE TITLE
pgf warning: ras image not found

### ISSUE THREAD

**Issue by brbarossa** [yihui/knitr#1218] opened 2016-05-27 12:51 UTC
Hello yihui,
thank you for your great project!

I think I ran into an issue that is bound to LaTeX and tikzDevice and external compilation:

``` tex
\documentclass{article}
\usepackage{tikz}

% Workaround
%\let\pgfimageWithoutPath\pgfimage 
%\renewcommand{\pgfimage}[2][]{\pgfimageWithoutPath[#1]{img/#2}}

<<>>=
library("ggplot2")                                         
opts_chunk$set(dev = "tikz",
               external = FALSE,
               fig.path = "img/R-")
@

\begin{document}                                                                  
  <<>>=
  x <- rnorm(1000)
  y <- rnorm(1000)

  ggplot(NULL, aes(x=x, y=y)) + geom_bin2d()
  @                                                                   
\end{document}
```

Following error is thrown (see also [here](https://tex.stackexchange.com/questions/127667/matplotlib-pgf-images-in-subdirectory)):

```
Package pgf Warning: File "R-unnamed-chunk-2-1_ras1" not found when defining image "pgflastimage". Tried all extensions in ".pdf:.jpg:.jpeg:.png:" on input line 1051.
```

Corresponding line in the tikz file:

``` tex
\pgfimage[width= 14.45pt,height= 72.27pt,interpolate=true]{R-unnamed-chunk-1-1_ras1}};
```

Obviously knitr gives tikzDevice no information about `fig.path`. I wasn't sure whether this project or tikzDevice would be more appropriate but I think it's an interaction between them.

Thanks for your help!

**Comment by yihui** [comment] 2016-11-05 04:41
Apparently you have found out the root cause, but I don't have time to fix it. It seems the .tikz file should be patched when external=FALSE.

Personally I think `external=TRUE` is a much better choice when combined with `cache=TRUE`. This can make the compilation a lot faster.

    \documentclass{article}
    \usepackage{tikz}
    
    <<>>=
    library("ggplot2")
    opts_chunk$set(dev = "tikz",
                   external = TRUE,
                   fig.path = "img/R-")
    @
    
    \begin{document}
      <<cache=TRUE>>=
      x <- rnorm(1000)
      y <- rnorm(1000)
    
      ggplot(NULL, aes(x=x, y=y)) + geom_bin2d()
      @
    \end{document}

**Comment by yihui** [comment] 2017-01-24 19:12
Closing since an alternative solution exists, and I probably won't have time to fix the original issue. Pull requests are always welcome!

**Closed by yihui** 2017-01-24 19:12 UTC
