### ISSUE TITLE
knitr unsupported on Rv3.5

### ISSUE THREAD

**Issue by madhan-s-d** [yihui/knitr#1662] opened 2019-01-29 12:11 UTC
@yihui 
Please be informed that, the knitr package does not seem to be supported on R 3.5.
However, the CRAN documentation says this package is supported from R >= 3.1.0.
Will support for 3.5 be provided any time soon please?

**Comment by yihui** [comment] 2019-01-29 14:27
Please clarify on "does not seem". I'm using R 3.5.2 myself and don't see any issues.

**Comment by madhan-s-d** [comment] 2019-01-30 06:50
Hi, please note that, we got the following error message, when we tried to install the knitr package in R 3.5 using the install.packages(...) command/statement.

_Warning messages:
package ‘knitr’ is not available (for R version 3.5.0)_

Please note that R is installed on Linux operating system (_RHELv7.5_).

**Comment by cderv** [comment] 2019-01-30 07:19
This is working for me with no warning if I download the source from CRAN 
``` r
url <- "https://cran.r-project.org/src/contrib/knitr_1.21.tar.gz"
pkg_knitr <- tempfile(fileext = ".tar.gz")
download.file(url, destfile = pkg_knitr, mode = "wb")
withr::with_temp_libpaths(
  install.packages(pkg_knitr, repos = NULL, type = "source")
)
#> Installing package into 'C:/Users/chris/AppData/Local/Temp/RtmpofqwM2/temp_libpath68f469e261db'
#> (as 'lib' is unspecified)
unlink(pkg_knitr)
```

<sup>Created on 2019-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I don't think this is an issue with knitr. You usually have this warning when `install.packages` try to check on CRAN during installation. Oddly, it should not check CRAN if you use `repos = NULL`

* Where did you get your source package ? 
* Can you try again to reinstall with a new tar.gz? you could also try `remotes::install_local("/home/xxyyzz/knitr_1.21.tar.gz")` but I do not understand why `install.packages()` would fail.

Thanks

**Comment by cderv** [comment] 2019-01-30 07:31
I understand that you don't have internet access. My reprex also download form internet locally before installing. and `install.packages(pkg_source, repos = NULL)` worked ok. 
I really don't think there is an issue with knitr. It is just an odd behavior I can't reproduce currently. 
Please, can you try again `install.packages(pkg_source, repos = NULL)` with a new downloaded bundle ? 

With your way of downloading prior installing, know that you will have to do that with every dependency, in order to have a 📦 to work. There are other solution to ease the process but it is a discussion for https://community.rstudio.com, not here.

**Comment by madhan-s-d** [comment] 2019-01-30 08:35
Yes it is a pain to track all dependencies and downloading them before hand.
We will download the package and its dependencies again, into a single directory and use the following command to install them.
_R> install.packages("/home/xxyyzz/knitr_1.21.tar.gz", repos = NULL, type="source", dependencies=TRUE)_
Thanks we will keep folks posted.

**Comment by cderv** [comment] 2019-01-30 19:05
I'll close this for now. You could reopen it if needed. 

Or better directly post in https://community.rstudio.com if you get further issue. 
There is a package management section and you'll find lots of advice on how to deal with offline environment.

thanks.

**Closed by cderv** 2019-01-30 19:05 UTC
