### ISSUE TITLE
Inline R code math shuold be automatically correctly formatted

### ISSUE THREAD

**Issue by yasirs** [yihui/knitr#1206] opened 2016-05-02 21:54 UTC
Consider the following .Rmd document

    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = TRUE)
    a <- anova(lm(cars$speed ~ cars$dist))
    pval <- a$`Pr(>F)`[1]
    ```
    The p-value for the dependence of speed on dist is `rpval`.
    ```{r cars}
    summary(cars)
    ```
This compiles for HTML or Word, but not for pdf. I am using the Rstudio menu for compiling. It spits the following error:

```
! Missing $ inserted.
<inserted text> 
                $
l.126 1.4898365\times

pandoc: Error producing PDF from TeX source
Error: pandoc document conversion failed with error 43
Execution halted
```

I don't think the user should have to manually insert $ signs around inline r code if they suspect certain signs will be used.

**Comment by yihui** [comment] 2016-05-03 02:17
Duplicate of https://github.com/rstudio/rmarkdown/issues/385

**Closed by yihui** 2016-05-03 02:17 UTC
