### ISSUE TITLE
Knitr stable not compatible with latest pandoc in archlinux systems

### ISSUE THREAD

**Issue by lf-araujo** [yihui/knitr#1459] opened 2017-11-16 23:55 UTC
As of today in Manjaro, pandoc is not receiving the --smart flag anymore, thus causing the documents not to render. 

```
/usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS 2017-11-16-growth-curve.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output /home/luis/Dropbox/Documentos/Psiquiatria/Projetos/NUSDAST/reports/2017-11-17-report.html --smart --email-obfuscation none --self-contained --standalone --section-divs --table-of-contents --toc-depth 3 --variable toc_float=1 --variable toc_selectors=h1,h2,h3 --variable toc_collapsed=1 --variable toc_smooth_scroll=1 --variable toc_print=1 --template /home/luis/R/x86_64-pc-linux-gnu-library/3.4/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --variable 'theme:bootstrap' --include-in-header /tmp/RtmpoMsB0k/rmarkdown-stre9d1443f8c1.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' 
--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
Try pandoc --help for more information.
Erro: pandoc document conversion failed with error 2
```

**Comment by yihui** [comment] 2017-11-17 03:31
Duplicate of https://github.com/rstudio/rmarkdown/issues/1120 (not a **knitr** issue).

**Closed by yihui** 2017-11-17 03:31 UTC
