### ISSUE TITLE
Customizing figure numbers from rmarkdown chunks

### ISSUE THREAD

**Issue by rraadd88** [yihui/knitr#1227] opened 2016-06-14 06:00 UTC
Hi yihui,

When I use this rmarkdown chunk,

`
'''{r figure_name,fig.cap="\\label{figure_name:cap}caption."} 
`
`
    -plotting-code-here-
`
`
'''
`
I get a figure caption like this,

`Figure 1: caption.`

But I need a caption like this,

`Figure S1: caption.`

How should I go about customizing the figure number in this way?

**Comment by yihui** [comment] 2016-06-14 14:15
Duplicate of https://github.com/rstudio/rmarkdown/issues/726

**Closed by yihui** 2016-06-14 14:15 UTC
