### ISSUE TITLE
knit2html ignores 'output' argument

### ISSUE THREAD

**Issue by julian-gehring** [yihui/knitr#935] opened 2015-01-14 14:41 UTC
```R
library(knitr)
knit2html(input = "~/knitr-html.Rhtml", output = "out.html")
```

always generates a `output` file derived from the `input` filename, and ignores the `output` argument. In this example, `knitr-html.html` is generated, not `out.html`. In constrast,

```R
knit(input = "~/knitr-html.Rhtml", output = "out.html")
```

works as expected

tested with knitr versions 1.8.15 and 1.8

**Comment by yihui** [comment] 2015-01-14 17:23
First, `knit2html()` is not designed for .Rhtml files. It is for R Markdown instead. You only need to call knit() for .Rhtml files, and the output will be .html; there is no need to use the markdown package to convert it to HTML again. You do get knitr-html.html in your case, and that is supposed to be the intermediate Markdown output file (.Rmd -> .md), which is to be converted to out.html.

Second, I cannot reproduce the problem if the input is an Rmd file. So I guess I can close this issue.

**Closed by yihui** 2015-01-14 17:23 UTC
