### ISSUE TITLE
Can't cross-reference when knitting to Word

### ISSUE THREAD

**Issue by MCM-Math** [yihui/knitr#1636] opened 2018-11-15 21:53 UTC
I'm not sure how to properly place references that would be in a Word document.  I tried putting it in square brackets, but that seems to reference file locations, not numbers for sections, figures, etc.

**Comment by cderv** [comment] 2018-11-16 13:42
Hello, 

why do you believe this a knitr issue ? Please provide some details if so. 

To use cross reference feature, you should have at bookdown 📦  and the single document feature
https://bookdown.org/yihui/bookdown/a-single-document.html

With `bookdown::word_document2()` rendering format, as explained in the book, you should be able to use cross reference as describe for [bookdown format](https://bookdown.org/yihui/bookdown/cross-references.html). Please give it a try - this is the recommanded format to use for such feature.

Also, for question-like issue, please use Stackoverflow or community.rstudio.com, there will be many experience users to help you and if at this end it is a bug or a feature request, you can post an issue in the correct repository.

**Comment by MCM-Math** [comment] 2018-11-16 14:02
Everything in the bookdown documentation I saw in terms of cross-referencing was for HTML and PDFs, not Word, so I felt this was the best place to start in terms of seeing if there is a solution, either directly through this package or by adding others as well.

**Comment by cderv** [comment] 2018-11-16 17:50
Thanks.
Know that all the syntax you'll found in the bookdown book that works in Rmarkdown document should work to render a single word document using `bookdown::word_document2`. It is not well developed because word is not the main used format. I let you try and seek for help if needed in https://community.rstudio.com

**Comment by yihui** [comment] 2018-11-16 20:20
Duplicate of https://github.com/rstudio/bookdown/issues/650

**Closed by yihui** 2018-11-16 20:20 UTC
