### ISSUE TITLE
sql chunk handles statements well with "Knit" but poorly with "Run"

### ISSUE THREAD

**Issue by itcarroll** [yihui/knitr#1637] opened 2018-11-15 23:50 UTC
Knitr appropriately handles chunks using the `sql` engine for statements (i.e. INSERT, UPDATE, CREATE, etc.) differently from how it handles chunks making queries (i.e. SELECT): it does not call `dbFetch`. In RStudio however, when you click "Run" (or the play button on a specific sql chunk), you get ugly results and a warning:

```
In result_fetch(res@ptr, n = n) :
  Don't need to call dbFetch() for statements, only for queries
```

The following Rmd is a reproduces the warning, if you run all the chunks rather than knit.

<pre><code>
---
editor_options: 
  chunk_output_type: inline
---

```{r}
library(RSQLite)
conn <- dbConnect(SQLite(), ":memory:")
```
```{sql, connection = conn}
CREATE TABLE test (
 id integer
)
```
```{sql, connection = conn}
SELECT * FROM test
```
```{r}
dbDisconnect(conn)
```
</code></pre>

My system information:
```
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RSQLite_2.1.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0      digest_0.6.18   rprojroot_1.3-2 DBI_1.0.0       backports_1.1.2
 [6] evaluate_0.12   blob_1.1.1      rmarkdown_1.10  tools_3.5.0     bit64_0.9-7    
[11] bit_1.1-14      yaml_2.2.0      compiler_3.5.0  pkgconfig_2.0.2 memoise_1.1.0  
[16] htmltools_0.3.6 knitr_1.20
```

**Comment by yutannihilation** [comment] 2018-11-16 04:06
Thanks, confirmed.

> Knitr appropriately handles chunks using the `sql` engine for statements

Unfortunately, it seems not. I guess it's just the warnings are not captured on knitting because it doesn't come from the chunks, but from knitr itself. The problem is here:

https://github.com/yihui/knitr/blob/dc5ead7bcfc0ebd2789fe99c527c7d91afb3de4a/R/engine.R#L550-L558

This probably should be something like below.

``` r
  if (is_sql_update_query(query)) {
    data = DBI::dbExecute(conn, query)
  } else if (is.null(varname) && max.print > 0) {
    res = DBI::dbSendQuery(conn, query)
    data = DBI::dbFetch(res, n = max.print)
    DBI::dbClearResult(res)
  } else {
    data = DBI::dbGetQuery(conn, query)
  }
```

**Comment by yutannihilation** [comment] 2018-11-17 01:45
@yihui I've modified the code and installed locally, but it seems RStudio still uses the unmodified version. Do you know when and where RStudio captures knitr's codes?

This is what I see with `debug(DBI::dbFetch)`. It says this function is in the namespace `tools:rstudio`, not in knitr namespace...

![image](https://user-images.githubusercontent.com/1978793/48655027-8805c780-ea55-11e8-98e9-6bc0832e049c.png)

**Comment by yihui** [comment] 2018-11-17 04:12
Interesting. Did you restart R?

**Comment by yutannihilation** [comment] 2018-11-17 04:39
Yes, I even restarted RStudio, but no luck...

**Comment by yutannihilation** [comment] 2018-11-26 10:13
> That's weird. I cannot reproduce your issue.

Really?? I cannot avoid reproducing this issue.... Here's what I did:

1. Install the patched branch.
``` r
devtools::install_github("yutannihilation/knitr@test-notebook-sql-chunk")
```
2. Close and relaunch RStudio.
3. Open a new R Markdown file, and copy and paste the above Rmd codes.
4. Run chunks by ▷ ("Run Current Chunk") buttons on the top right of the chunks.

And I still see the warning...:

![image](https://user-images.githubusercontent.com/1978793/49007606-38d73980-f1af-11e8-872a-1bc10fc5a207.png)

> patch the next if statement, too:

Thanks for pointing out! I got the error when I pushed knit button.

**Comment by yutannihilation** [comment] 2018-12-04 07:47
TIL: `Run` button is out of knitr's control and we need to fix RStudio...

https://community.rstudio.com/t/where-is-knitr-used-by-rstudio/19244/4

**Comment by yihui** [comment] 2018-12-04 14:55
Hmm. I didn't know that. So we'll have to fix both knitr and RStudio? If [the patch above](#issuecomment-440799438) looks good to you, please feel free to push it to the master branch (I can do it, too). Thanks!

**Comment by yutannihilation** [comment] 2018-12-04 23:35
Done!

https://github.com/yihui/knitr/commit/7b737bdc85b433a787367d6ba87c61c53d2144c9

I'll send a PR to RStudio as well. May I keep this open until it's merged?

**Comment by yutannihilation** [comment] 2018-12-06 22:37
https://github.com/rstudio/rstudio/pull/3991 is merged. So, this should be fixed in the next release of RStudio.

**Closed by yutannihilation** 2018-12-06 22:37 UTC

**Comment by yihui** [comment] 2018-12-06 22:41
Great. Thanks again!
