### ISSUE TITLE
Header row formatting in markdown kable tables breaks after html table

### ISSUE THREAD

**Issue by jacob-long** [yihui/knitr#1607] opened 2018-09-20 19:48 UTC
This may be a pandoc problem, but I'm not sure.

Basically, there's a problem that I believe relates to the empty column name that is produced when `kable(x, row.names = TRUE)` is called in markdown format *after* an HTML table has been inserted in the document. I haven't tested every possible combination of factors but this certainly causes the issue.

Here's a reprex:
````
---
title: "Test"
output: 
  html_document
---

```{r}
knitr::kable(head(mtcars, 3), row.names = TRUE)
```

```{r}
knitr::kable(head(mtcars, 3), format = "html", row.names = TRUE)
```

```{r}
knitr::kable(head(mtcars, 3), row.names = TRUE)
```

````

The first table will look like this, as expected:

![](https://i.imgur.com/KX8RxLy.png)

But the third table looks like this:

![](https://i.imgur.com/QAMkaRc.png)

The markdown for table 1:

```
                  mpg   cyl   disp    hp   drat      wt    qsec   vs   am   gear   carb
--------------  -----  ----  -----  ----  -----  ------  ------  ---  ---  -----  -----
Mazda RX4        21.0     6    160   110   3.90   2.620   16.46    0    1      4      4
Mazda RX4 Wag    21.0     6    160   110   3.90   2.875   17.02    0    1      4      4
Datsun 710       22.8     4    108    93   3.85   2.320   18.61    1    1      4      1

```

and table 3

```
                  mpg   cyl   disp    hp   drat      wt    qsec   vs   am   gear   carb
--------------  -----  ----  -----  ----  -----  ------  ------  ---  ---  -----  -----
Mazda RX4        21.0     6    160   110   3.90   2.620   16.46    0    1      4      4
Mazda RX4 Wag    21.0     6    160   110   3.90   2.875   17.02    0    1      4      4
Datsun 710       22.8     4    108    93   3.85   2.320   18.61    1    1      4      1
```

appear identical.

This is why I say it may be a pandoc issue. 

This can be fixed by changing the `knitr.table.format` option to `"markdown"` (which produces a different flavor of markdown table than `"pandoc"` for reasons unclear to me) but I'm reporting this because it seems like a bizarre default behavior. It took quite a while for me to figure out what was going on and I'm a package developer who has spent quite a bit of time using `knitr` and `kable` specifically. I suspect this would be very confusing to many other end users.

FWIW, I encountered this issue because I used another package that had `knit_print`s HTML tables and subsequently saw this odd formatting for all subsequent direct calls to `kable`. Obviously most people won't be using the `format` argument to `kable`, but it will be more common that someone may use a third-party package that outputs HTML.

**Comment by cderv** [comment] 2021-01-28 14:38
This can't be reproduce as is anymore - the example above give the correct result. But I think this is because **knitr** now defaults to `pipe` table (3373ebef7b0c8aef46587a9c1e74aa45f5930909 with PR #1830) 

It is possible it has also fix this. 

But using specifically `pandoc` format (and so `simple` table), it is not reproducible 
````markdown
---
title: "Test"
output: 
  html_document:
    keep_md: true
---

```{r}
knitr::kable(head(mtcars, 3), format = "pandoc", row.names = TRUE)
```

```{r}
knitr::kable(head(mtcars, 3), format = "html", row.names = TRUE)
```

```{r}
knitr::kable(head(mtcars, 3), format = "pandoc", row.names = TRUE)
```

````

I'll close this then. Maybe recent Pandoc have fix that. 

Thanks for the report, and thank you for your patience with this issue.

**Closed by cderv** 2021-01-28 14:38 UTC
