### ISSUE TITLE
RStudio in German Locale fails to compile

### ISSUE THREAD

**Issue by dmenne** [yihui/knitr#987] opened 2015-04-08 14:01 UTC
The default RStudio document in German locale does not compile in pdf-mode and gives the highly confusing error message:

```
! Incomplete \iffalse; all text was ignored after line 102.
<inserted text> 
                \fi 
<*> ./tex2pdf.8352/input.tex
```

This is caused by the date (8. April) which seems to be considered starting an enumeration. Remove the period after the number, and it compiles.

In HTML Mode, there also is an error with date->period, but the result is more of the funny type and can be easily spotted.

```
---
title: "Untitled"
author: "DM"
date: "8. April 2015"
output: pdf_document
---

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, 
```

**Comment by yihui** [comment] 2015-04-10 02:02
Duplicate of https://github.com/rstudio/rmarkdown/issues/145 and https://github.com/rstudio/rmarkdown/issues/173

**Closed by yihui** 2015-04-10 02:02 UTC
