### ISSUE TITLE
Pandoc 2.0.1 error when knitting to html

### ISSUE THREAD

**Issue by alxsimon** [yihui/knitr#1453] opened 2017-11-02 15:59 UTC
I am having problems knitting to html with the latest versions of pandoc.
I am using the latest version of knitr (1.17) through Rstudio on mac os 10.13.
Pandoc is installed via homebrew.

The problems are occuring with versions 2.0.0.1 and 2.0.1 of pandoc.
When downgrading to pandoc 1.19.2.4 it works.

When knitting I end up with this error message:
`/usr/local/bin/pandoc +RTS -K512m -RTS Crosses_analysis.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output Crosses_analysis.html --smart --email-obfuscation none --self-contained --standalone --section-divs --table-of-contents --toc-depth 3 --template /Users/alexis/Library/R/3.4/library/rmarkdown/rmd/h/default.html --highlight-style haddock --number-sections --variable 'theme:bootstrap' --include-in-header /var/folders/pn/4yyvllx13y74b5xr91zq2xy40000gn/T//Rtmp1HEA9i/rmarkdown-str5ddb4d647c90.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' `

`--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
Try pandoc --help for more information.
Erreur : pandoc document conversion failed with error 2`

For now I will use the old version of pandoc.
All the best.

**Comment by yihui** [comment] 2017-11-02 16:45
Duplicate of https://github.com/rstudio/rmarkdown/issues/1184

**Closed by yihui** 2017-11-02 16:45 UTC
