### ISSUE TITLE
Blank figure for certain syntax

### ISSUE THREAD

**Issue by Courvoisier13** [yihui/knitr#1325] opened 2016-11-29 13:38 UTC
Hi, I have this weird issue:
[](https://github.com/wilkelab/cowplot/issues/51)
I think it's a `knit` issue. 
I will repeat it here.

In the following the pdf produced is blank:
Rnw file: 
```
\documentclass{article}
\begin{document}
\begin{center}
<<echo=FALSE, out.width='1\\linewidth', fig.width=15, fig.height=17, warning=FALSE, message=FALSE >>=

if(T){
	library(cowplot)
	p = ggplot(pressure, aes(temperature, pressure)) + geom_line()
	p_1 = plot_grid(p, p, labels = c("A", "B"))
	p_2 = plot_grid(p, p, labels = c("A", "B"))
	plot_grid(p_1, p_2, ncol = 1)
}

@
\end{center}
\end{document}

```

In Rstudio, I source the Rnw (this step is important). If a figure exists in the Rstudio UI, I run the following:

```
library(knitr)
compiler = "xelatex"
outTex = "test2.tex"
outPdf = "test2.pdf"
src = "test2.Rnw"
outTexFile = knit(src, output = outTex, quiet = T)
Sys.setenv(PDFLATEX = compiler)
buff = tools::texi2pdf(file = outTexFile, clean = T)
```

The pdf produced is blank.

When I use the following Rnw (notice the # at the end of the chunk):

```
\documentclass{article}
\begin{document}
\begin{center}
<<echo=FALSE, out.width='1\\linewidth', fig.width=15, fig.height=17, warning=FALSE, message=FALSE >>=

if(T){
	library(cowplot)
	p = ggplot(pressure, aes(temperature, pressure)) + geom_line()
	p_1 = plot_grid(p, p, labels = c("A", "B"))
	p_2 = plot_grid(p, p, labels = c("A", "B"))
	plot_grid(p_1, p_2, ncol = 1)
}
#
@
\end{center}
\end{document}

```
Then the figure appears in the pdf.
If I do `dev.off()` then the figures appears in the pdf in both cases.

The problem is related to the graphics devices. `knit` seems to be calling the graphics device another time if that one is not empty. If the device is not null, then using knit as above will create another figure in the Rstudio UI. If not, it will stay empty.

**Comment by yihui** [comment] 2016-11-29 18:30
@Courvoisier13 In general, I'd recommend you to knit a document in a clean R session, e.g. click the Compile PDF button instead of running `knitr::knit()` in an interactive R session. That said, I was able to reproduce this issue in the RStudio IDE.

@jjallaire Here is a minimal example:

```r
\documentclass{article}
\begin{document}
<<echo=FALSE>>=
library(cowplot)
p = ggplot(pressure, aes(temperature, pressure)) + geom_line()
p_1 = plot_grid(p, p, labels = c("A", "B"))
p_2 = plot_grid(p, p, labels = c("A", "B"))
plot_grid(p_1, p_2, ncol = 1)
@
\end{document}
```

If you run the code chunk in the IDE, then `knitr::knit()` the Rnw file, the plot will be missing. I observed an issue during debugging:

The plot is not complete in the plot pane after you run the code chunk (it becomes complete after I resize the pane and wait for a while):

![image](https://cloud.githubusercontent.com/assets/163582/20722911/084982aa-b62e-11e6-88c6-fb876422c87e.png)

I'm not sure if is the reason why the plot is missing in the .tex file. I feel there are some plot hooks running behind the scenes, which might have interfered knitr's plot capturing.

**Comment by Courvoisier13** [comment] 2016-12-01 08:06
Thanks @yihui . In my case all 4 plots appear in the IDE. 
btw, I added the 4 plots because it seems like it's a cowplot issue and not in general. If I use the grid package then there is no problem.

**Comment by yihui** [comment] 2017-01-24 19:10
Closing this issue since I don't know what to do for it (rendering in a new session by clicking the Knit button may be a better idea). Sorry.

**Closed by yihui** 2017-01-24 19:10 UTC
Labels: Bug

**Comment by Courvoisier13** [comment] 2017-01-24 21:28
Ok. thank you.
