### ISSUE TITLE
Strange behavior with print(kable(...)) immediately followed by a plot in R Markdown

### ISSUE THREAD

**Issue by eheinzen** [yihui/knitr#1510] opened 2018-02-14 20:25 UTC
I don't think this has been reported here, but I'm having a strange issue with a plot immediately after I print a kable object in an R Markdown script.  Here's a reproducible example:

````
---
output: html_document
---

```{r echo = FALSE, results = 'asis'}
library(ggplot2)
library(knitr)
dat <- data.frame(var1 = 1, var2 = 2)
print(kable(dat)) ## getting rid of print() fixes the problem
# cat("\n") ## uncommenting this this fixes the problem
ggplot(dat, aes(x = var1, y = var2)) + geom_point()
```

```{r}
sessionInfo()
```
````

Here's what it looks like when I knit it:
![image](https://user-images.githubusercontent.com/30500972/36226145-9f5f3d0e-1192-11e8-8b27-f9f50d579ec7.png)

There are two things that I noticed fix the problem:
- Remove the print() call -- I can't do this if, e.g., I'm in a for-loop
- cat out a newline character -- this is annoying, but I'll live with it if I have to

**Comment by eheinzen** [comment] 2018-02-14 20:34
Update: I just discovered the knit_print function, which works when you knit the Rmd, but isn't pretty when you run this code in the command line (hence why I like using print())

**Comment by cderv** [comment] 2021-01-21 21:13
@eheinzen sorry for the delay. is it still an issue ? 

I can't reproduce using your Rmd above with latest versions of packages. it is possible that it has been fixed in a way. 

I'll close but feel free to reopen if I missed something.

**Closed by cderv** 2021-01-21 21:13 UTC

**Comment by eheinzen** [comment] 2021-01-22 18:12
I must've made a workaround at the time, and haven't noticed it of late.  Thanks for closing.
