### ISSUE TITLE
Cannot knit after update to pandoc

### ISSUE THREAD

**Issue by kstagaman** [yihui/knitr#1454] opened 2017-11-03 17:53 UTC
After updating to the latest version of pandoc (`pandoc 2.0.1
Compiled with pandoc-types 1.17.2, texmath 0.9.4.4, skylighting 0.4.2`), I can no longer get anything to knit properly. I get the same error even with just using the Rmarkdown default template in Rstudio as I've copied below.

````
---
title: "test"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.

When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:

```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
````

Trying to knit generates the error: ```--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.```

I'm using knitr version 1.17.9

**Comment by yihui** [comment] 2017-11-04 02:33
Duplicate of #1453

**Closed by yihui** 2017-11-04 02:33 UTC
