### ISSUE TITLE
Setting `eval = FALSE` globally doesn't comment R code when `purl()`-ing

### ISSUE THREAD

**Issue by cderv** [yihui/knitr#2103] opened 2022-02-03 17:25 UTC
Related to discussion for https://github.com/mlverse/torch/issues/765

It seems like setting 
```r
knitr::opts_chunk$set(eval = FALSE)
```

in a vignette will make chunks NOT be included for execution in the resulting R scripts. This means like the vignette on CRAN will be checked by running purl then executing the R file which will error (as the chunks are not made to be run on CRAN). 

If the options is set on the chunk it is taken into account it seems 
https://github.com/yihui/knitr/blob/887fc44cadea648b562c2cf7065199b603975dd5/R/hooks-extra.R#L151

Is this expected ? 
`vweave` and `vtangle` of **knitr** are not the easiest to understand. So maybe I am missing something

cc @dfalbel

**Comment by yihui** [comment] 2022-03-04 19:17
This is indeed difficult to understand or explain. In short, personally I'm against the idea of checking the R scripts generated from vignettes during `R CMD check`: https://stat.ethz.ch/pipermail/r-devel/2014-May/069113.html but R core didn't agree with me.

Since `purl()` can't reliably generate a script that is equivalent to the code actually executed by `knit()` (because `purl()` doesn't run any code, e.g., it wouldn't run `opts_chunk$set()` in code chunks), I had three hacks in **knitr** to address the problem.

First, the R script is actually generated by `hook_purl()` instead of `purl()`: https://github.com/yihui/knitr/blob/8ce5e5ce2297335be9835b80270929c5607204fe/R/hooks-extra.R#L136

https://github.com/yihui/knitr/blob/8ce5e5ce2297335be9835b80270929c5607204fe/R/utils-vignettes.R#L35

`hook_purl()` is executed during `knit()`, so it's aware of things like `opts_chunk$set()`. I don't know why it didn't work for **torch** package vignettes.

Second, I have tried to disable regenerating R scripts during `R CMD check`: https://github.com/yihui/knitr/blob/8ce5e5ce2297335be9835b80270929c5607204fe/R/utils-vignettes.R#L42-L48

I don't know why it didn't work for **torch**. There was a brief regression 87d094a6c593c31a3667821865e91b4a530018ec but I think it should be very unlikely that the problem was caused by this regression (it only existed for one day---introduced in knitr 1.35 and fixed in 1.36 released one day later).

Third, to truly disable generating R scripts from vignettes, package authors can use the `*_notangle` vignette engines, e.g., 

```
  %\VignetteEngine{knitr::rmarkdown_notangle}
```

https://yihui.org/knitr/demo/vignette/#vignette-engines

Anyway, I can't think of a possible explanation to the original problem. The error log has been deleted on CRAN, and I don't know what the error was now.

If we can reproduce this problem in a minimal example, we can investigate again. For now, I'm closing this issue since we haven't received any other similar reports. It's probably a transient issue. Thanks!

**Closed by yihui** 2022-03-04 19:17 UTC
