### ISSUE TITLE
kable produces malformed reference links after HTML calls in blogdown

### ISSUE THREAD

**Issue by oganm** [yihui/knitr#1669] opened 2019-02-06 21:36 UTC
I have asked this question in [stackoverflow](https://stackoverflow.com/questions/54545733/kable-produces-malformed-reference-links-within-lapply-function-in-blogdown) too but did not get an answer yet.

The gist of it is, within a freshly created blogdown page, creating a table using `kable` causes the caption to be edited to include a reference link and a table count (eg. "Table 1: Intended Caption"). This is undesirable for me but I assume it is intended behaviour.

However this behaviour changes when `kable` is called from within pretty much anything that uses a `{`. The reference link is added by appending a `(\#tab:codeblocklabel)` in the beginning of each table which html just shows as plain text.

Here is an an example post that highlights the problem. Here `test1`'s caption is processed correctly but all the others use the `(\#tab:codeblocklabel)` format.

    ---
    title: test
    author: ''
    date: '2019-02-05'
    slug: test
    categories: []
    tags: []
    ---
   
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(collapse = TRUE)
    ```
    
    ```{r test1}
    library(knitr)
    library(magrittr)
    library(kableExtra)
    library(shiny)
    
    data.frame(a= c(1,2,3)) %>% kable(caption = 'test',format = 'html')
    
    ```

    ```{r test2}
    
    lapply(1:2,function(x){
        data.frame(a= c(1,2,3)) %>% kable(caption = 'test2',format = 'html') %>% HTML()
    }) -> tables
    
    tables[[1]]
    
    tables[[2]]
    ```

    ```{r test3}
    for(i in 1){
      table = data.frame(a= c(1,2,3)) %>% kable(caption = 'test3',format = 'html') %>% HTML()
    }
    table
    ```

    ```{r test4}
    {data.frame(a= c(1,2,3)) %>% kable(caption = 'test4',format = 'html') %>% HTML()}
    ```

As stated on the stackoverflow I was able to identify the code that causes this behaviour in the `create_label` function but could not understand how "bookdown.internal.label" is set or can be modified.

Ultimately, I don't want my captions to be edited by kintr at all. But the second behaviour is clearly wrong and unintentional while the first is probably a sensible default (though I would appreciate some hints in getting rid of that too).

**Comment by tcgriffith** [comment] 2019-02-07 01:43
i tested your example post and all of the tables appear the same. Can you add a screenshot? thanks!

**Comment by oganm** [comment] 2019-02-07 01:50
![image](https://user-images.githubusercontent.com/6352379/52385703-a0bfc100-2a37-11e9-9e00-e974958c5541.png)

**Comment by oganm** [comment] 2019-02-07 01:54
Note that this is how blogdown renders the file. If you just knit it, you will get unmodi

**Comment by tcgriffith** [comment] 2019-02-07 03:55
Unable to reproduce the issue in my blogdown site. maybe it's related to the specific theme. which theme are you using? Please show us your repo.

**Comment by oganm** [comment] 2019-02-07 04:12
This is the default theme ("yihui/hugo-lithium"). I simply ran

```
blogdown::new_site()
blogdown::new_post("test", ext = ".rmd")
```

And edited the `content/post/2019-02-05-test.Rmd` file to include the code posted above. Everything else is untouched. Then

```
blogdown::serve_site()
```

You can find the output [here](https://github.com/oganm/bgtest) freshly re-created

**Comment by oganm** [comment] 2019-02-08 01:29
It seems like it is related to the HTML call I appended after kables. The issue occurs at the point of coercing into a character and has nothing to do with `{`s. If I replace
```
data.frame(a= c(1,2,3)) %>% kable(caption = 'test',format = 'html')
```

with

```
data.frame(a= c(1,2,3)) %>% kable(caption = 'test',format = 'html') %>% as.character()
```
I get
```html
## [1] "<table>\n<caption>(\\#tab:test1)test</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> a </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 1 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n</tbody>\n</table>"
```
as the output which is what appears in my previous malformed tables. If I replace that `as.character` with `HTML`, I get the same malformed table caption. This suggests the issue has nothing to do with `{`s. I suspect in blogdown and bookdown, knitr outputs the files with the malformed captions which are later processed by something else to add the table numbers.

**Comment by yihui** [comment] 2019-03-07 20:38
Duplicate of https://github.com/rstudio/blogdown/issues/367

**Closed by yihui** 2019-03-07 20:38 UTC
