### ISSUE TITLE
Incorrectly placed caption in kable pandoc output 

### ISSUE THREAD

**Issue by renkun-ken** [yihui/knitr#1083] opened 2015-08-03 12:08 UTC
Create a new rmd and put a chunk like

```r
library(knitr)
kable(head(mtcars))

kable(head(mtcars), format = "pandoc", caption = "table 2")
```

or separate chucks but with `echo=FALSE`, producing

![knitr_kable_pandoc](https://cloud.githubusercontent.com/assets/4662568/9037180/3259f934-3a1b-11e5-97be-a599b3a5a68b.png)

The caption of table 2 goes to table 1. It seems that pandoc recognizes table captions below the table in default, but the behavior of `kable` does not produce expected result in this case.

https://github.com/renkun-ken/formattable/issues/23 depends on this issue.

**Comment by yihui** [comment] 2015-08-11 23:48
Duplicate of #895. Thanks!

**Closed by yihui** 2015-08-11 23:48 UTC

**Comment by renkun-ken** [comment] 2015-08-12 01:12
Thanks for the solution/hack!
