### ISSUE TITLE
Difficulty in using `class.output` option with `collapse=T`

### ISSUE THREAD

**Issue by benwhalley** [yihui/knitr#2172] opened 2022-09-20 13:41 UTC
This reopens this issue: https://github.com/yihui/knitr/issues/1906

These screenshots illustrate the problem. The only thing that changes is the value for `collapse` chunk option:

### With `collapse = F`

<img width="1081" alt="Screenshot 2022-09-20 at 14 35 28" src="https://user-images.githubusercontent.com/524696/191272423-816bcd78-8ffd-4fae-bd02-3c8dea401f0c.png">

### With `collapse = T`
<img width="1177" alt="Screenshot 2022-09-20 at 14 35 11" src="https://user-images.githubusercontent.com/524696/191272440-1da39543-ba78-43a5-843f-62a936a10d29.png">

-------------------

Minimal example is here: https://gist.github.com/benwhalley/99b2ebf4b58605e0cec35727793190f6

I can see there was some previous discussion about expected behaviour, but the problem problem is that if collapse=T then no distinction is made between the R code being echoed and the resulting output (and no different css is applied, so results can't be styled differently to commands).

I can see that for the second code chunk it's not obvious which classes to output, but at the very least allowing the author to know that something is a result rather than the command that produced it would be very useful. 

In my case, I could just set collapse=F but this results in very fragmented commands and output which is less good for explanatory purposes.

**Comment by cderv** [comment] 2022-09-21 09:14
The purpose of `collapse = TRUE` is to collapse all the source and output blocks from one code chunk into a single bloc. 
This means on HTML side it will be in one `<pre><code>` block by design. This will also mean that syntax highlighting will apply on the all block usually. 

> the problem problem is that if collapse=T then no distinction is made between the R code being echoed and the resulting output (and no different css is applied, so results can't be styled differently to commands).

Usually when setting `collapse = TRUE` as a global option, one want also to set for example the `comment` option to help differentiate code and result as you explain. 

````r
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
````
![image](https://user-images.githubusercontent.com/6791940/191460199-3e5ec359-b59e-4ade-b37d-bfafd0c8410a.png)

See for example [R4DS](https://r4ds.had.co.nz/tibbles.html#creating-tibbles) book.

A prompt could be added for R code line but this is not good for highlighting
````
knitr::opts_chunk$set(
  collapse = TRUE,
  prompt = TRUE
)
````
![image](https://user-images.githubusercontent.com/6791940/191460440-e93006f2-9805-41d1-8861-9932e50d1ce8.png)

> this results in very fragmented commands and output which is less good for explanatory purposes.

You could also look at tweaking the CSS for leaving less space between the source block and result block maybe. 


I don't really know what we could do to change this. Do you have suggestion based on the current structure of HTML produce when `collapse = TRUE` ? What would you expect at results exactly ? Is it really collapsing or just a different CSS styling to closer match results chunks with their source code maybe ?

**Comment by benwhalley** [comment] 2022-09-21 09:22
Ideally the default would be that this:

```{r}
mean(mtcars$mpg)
```

Would produce something like:

```
<pre>
<span class="code">
mean(mtcars$mpg)
</span>
<span class="output">
[1] 20.09062
</span>
</pre>
```

This way you could style the code and output differently. 

The problem with having a prefix for results or messages (e.g. `#>` or `##`) is that it makes it hard to copy and paste. For code especially, this really confuses students/beginners who often copy the prompt. I know this seems a silly error, but it is _incredibly_ common... I teach R and stats to 1st and 2nd year UGs and see this every year despite help from staff.

If you also then set output classes it would be possible to have:


```{r}
mean(mtcars$mpg)
warning("hello")
```

Would produce something like:

```
<pre>
<span class="code">
mean(mtcars$mpg)
</span>
<span class="output bg-success">
[1] 20.09062
</span>
<span class="code">
warning("hello")
</span>
<span class="output bg-warning">
Hello
</span>
</pre>
```

**Comment by benwhalley** [comment] 2022-09-21 09:27
Just to add, an example here: https://codepen.io/benwhalley/pen/jOxLEoo

I realised that spans within pre tags wouldn't allow a background color, so divs might be better.  Either would be better than current behaviour thought I think.

**Comment by cderv** [comment] 2022-09-21 10:20
One thing is that **knitr** does not produce the HTML structure of the code. **knitr** will produce markdown content, to be converted to HTML or PDF or else, by Pandoc.  https://bookdown.org/yihui/rmarkdown-cookbook/rmarkdown-process.html

So when  setting `collapse = TRUE`, this chunk  
````
```{r}
mean(mtcars$mpg)
```
````
will produce this markdown in the intermediate `.md` file
````
```r
mean(mtcars$mpg)
## [1] 20.09062
```
````

(by default, `comment = "##"` which allows to differentiate code from result in the output, but you removed it )

It will be converted to HTML by Pandoc to `<pre><code>` structure, and then the HTML content structure will be  created by syntax highlighter used (by default highlight..js, but could be Pandoc own system) - https://pkgs.rstudio.com/rmarkdown/reference/html_document.html#highlighting-1

So there is no control over what you expect unfortunately. 

Regarding `<span>` or `<div>` inside `<pre>`, I don't think it is that common. `<pre><code>` is expected by most of the tools to detect code part in a page, especially for highlighting (For example [highlight.js](https://highlightjs.org/usage/)). 

Even if we could come up with a new way to change the structure (which **downlit** R package is doing), we could also need to come up or tweak the syntax highlighter. 

Overall it is not that obvious, and we won't probably change this in **knitr** at this is not the correct level. It would need to be in one of the syntax highligther but they usually are static analysis only and don't know results or it would need to be a specific R tools (like **downlit**) for this specific usage, that would use special [knitr hooks](https://bookdown.org/yihui/rmarkdown-cookbook/output-hooks.html) to output directly a structure like you want. Problem of syntax highlighting would need to be handled specifically too. 

> The problem with having a prefix for results or messages (e.g. #> or ##) is that it makes it hard to copy and paste.

The comment part is here by default so that when copying the code chunk content from the collapse block, this is still valid R code. R expression does get evaluated when paster, while results being commented they are ignored.


> For code especially, this really confuses students/beginners who often copy the prompt. I know this seems a silly error, but it is incredibly common... I teach R and stats to 1st and 2nd year UGs and see this every year despite help from staff.

Just to shere, there are some tools to add a copy button in chunks like [`xaringanExtra::use_clipboard()`](https://pkg.garrickadenbuie.com/xaringanExtra/#/clipboard)`or https://github.com/RLesur/klippy

This exists in **bookdown** too but we still need to make it clever to ignore prompt and results https://github.com/rstudio/bookdown/issues/1072

So we could probably add to **rmarkdown** as default feature to add a clever copy button that would keep only the code to avoid copy issues. 

I hope this clarify the topic and challenge about this.

**Comment by cderv** [comment] 2022-09-21 14:52
You may be looking for `results = "hold"`

![image](https://user-images.githubusercontent.com/6791940/191537663-661a7fdf-edcb-4b65-8e6c-fc3ebbb7e60d.png)

Is it closer to what you are looking for ?

**Comment by dmurdoch** [comment] 2023-01-25 21:15
I've just noticed that `collapse = TRUE` also messes up handling of `htmlwidgets` output.  I saw it first in `rgl`, but it's also present in `leaflet`.  For example, with `collapse = TRUE` this code chunk
````
```{r collapse = TRUE, comment = "#>"}
library(leaflet)
leaflet() %>% addTiles()

# This is some more code after the widget
123
```
````
renders like this in an `html_vignette`:
![Screen Shot 2023-01-25 at 4 12 51 PM](https://user-images.githubusercontent.com/1935680/214692061-ff544364-0519-4615-ab6d-58e5a2c13d94.png)

Notice that the final comment and expression aren't typeset as code, they are typeset as regular text.  The same problem happens in `html_document`. The Markdown produced by `rmarkdown::render()` looks like this:

````
```r
library(leaflet)
leaflet() %>% addTiles()
```

```{=html}
<div class="leaflet html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-067772b9251e7c9c20ad" style="width:288px;height:288px;"></div>
<script type="application/json" data-for="htmlwidget-067772b9251e7c9c20ad">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addTiles","args":["https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",null,null,{"minZoom":0,"maxZoom":18,"tileSize":256,"subdomains":"abc","errorTileUrl":"","tms":false,"noWrap":false,"zoomOffset":0,"zoomReverse":false,"opacity":1,"zIndex":1,"detectRetina":false,"attribution":"&copy; <a href=\"https://openstreetmap.org\">OpenStreetMap<\/a> contributors, <a href=\"https://creativecommons.org/licenses/by-sa/2.0/\">CC-BY-SA<\/a>"}]}]},"evals":[],"jsHooks":[]}</script>

# This is some more code after the widget
123
#> [1] 123
```

````

**Closed** 2023-02-15 20:42 UTC
