### ISSUE TITLE
encoding issue in metadata

### ISSUE THREAD

**Issue by stla** [yihui/knitr#1400] opened 2017-05-12 09:32 UTC
Hello, 

 I don't know whether this is an issue with `knitr`, `rmarkdown` or RStudio.
I have metadata like this:
```
---
title: "Dyadic expansion with R"
author: "Stéphane Laurent"
date: '`r Sys.Date()`'
output:
  md_document:
    toc: yes
    variant: markdown
  html_document:
    keep_md: yes
---
```
When I click on *"Knit to html"* in RStudio, the two fields `md_document` and `html_document` are automatically exchanged. But then my first name becomes **StÃ©phane**.

**Comment by yihui** [comment] 2017-05-12 18:37
For the encoding issue, `devtools::session_info('rmarkdown')` please.

It is by design of the RStudio IDE that the two fields are exchanged. When you knit to a specific output format, that format will be raised to the first item of the `output` field. I'm not sure if this will change in the future, but it is an RStudio IDE issue anyway.

**Comment by stla** [comment] 2017-05-12 19:00
Hello Yihui. I didn't know this command.

```
> devtools::session_info('rmarkdown')
Session info ----------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.3 (2017-03-06)
 system   x86_64, mingw32             
 ui       RStudio (1.0.143)           
 language EN                          
 collate  French_Belgium.1252         
 tz       Europe/Paris                
 date     2017-05-12                  

Packages --------------------------------------------------------------------------------------
 package   * version date       source                            
 backports   1.0.5   2017-01-18 CRAN (R 3.3.2)                    
 base64enc   0.1-3   2015-07-28 CRAN (R 3.3.2)                    
 bitops      1.0-6   2013-08-17 CRAN (R 3.3.2)                    
 caTools     1.17.1  2014-09-10 CRAN (R 3.3.3)                    
 digest      0.6.12  2017-01-27 CRAN (R 3.3.3)                    
 evaluate    0.10    2016-10-11 CRAN (R 3.3.3)                    
 highr       0.6     2016-05-09 CRAN (R 3.3.3)                    
 htmltools   0.3.6   2017-04-28 CRAN (R 3.3.3)                    
 jsonlite    1.4     2017-04-08 CRAN (R 3.3.3)                    
 knitr       1.15.20 2017-04-28 Github (yihui/knitr@f3a490b)      
 magrittr    1.5     2014-11-22 CRAN (R 3.3.3)                    
 markdown    0.8     2017-04-20 CRAN (R 3.3.3)                    
 mime        0.5     2016-07-07 CRAN (R 3.3.2)                    
 Rcpp        0.12.10 2017-03-19 CRAN (R 3.3.3)                    
 rmarkdown   1.5     2017-04-29 Github (rstudio/rmarkdown@95b8b1f)
 rprojroot   1.2     2017-01-16 CRAN (R 3.3.3)                    
 stringi     1.1.3   2017-03-21 CRAN (R 3.3.3)                    
 stringr     1.2.0   2017-02-18 CRAN (R 3.3.3)                    
 yaml        2.1.14  2016-11-12 CRAN (R 3.3.3)   
```

**Comment by yihui** [comment] 2017-05-12 19:57
Oh I just realized you said your name was garbled because you clicked the Knit HTML menu (I thought you saw garbled characters in the HTML output). In that case, it is an issue of the RStudio IDE.

Cc @jmcphers @jjallaire

**Comment by stla** [comment] 2017-05-12 21:59
Yes, this occurs in the source `Rmd` file.

**Comment by yihui** [comment] 2017-05-18 18:45
It seems the same issue has been reported at https://github.com/rstudio/rmarkdown/issues/998, so I'm closing this one.

**Closed by yihui** 2017-05-18 18:45 UTC
