### ISSUE TITLE
Error in R Markdown : Knit HTML (Object Not found )

### ISSUE THREAD

**Issue by LucianoSP** [yihui/knitr#1065] opened 2015-07-03 12:53 UTC
Im having a problem (I believe related to encoding). When I run my code in Rstudio it works and outputs the expected result. When I try to knit HTML document, it gives an error (object not found). The object name (variable) has characters like çãó...)

Here is the code:

 ```{r}
library(dplyr)
library(knitr)
setwd("~/GitHub/Servidores/Servidores")
camara = read.table("camara.csv", sep = ";", header = TRUE, fill = TRUE,  quote = "", dec = ",", fileEncoding = 'ISO8859-1')

camara$Cargo.Individualizado.do.Servidor = as.character(camara$Cargo.Individualizado.do.Servidor)
camara$Cargo = gsub("[0-9]*$", "", camara$Cargo.Individualizado.do.Servidor)
camara = camara %>% mutate(REMUNERACAO_BRUTA = Remuneração.Fixa + Vantagens.de.Natureza.Pessoal + Função.ou.Cargo.em.Comissão + Outras.Remunerações.Eventuais.Provisórias... + Abono.de.Permanência)

```

```{r kable}
a = camara %>% group_by(Cargo) %>% filter(Remuneração.Fixa != 0 & !is.na(Remuneração.Fixa)) %>% summarise(N_Servidores = n(), Rem_Bruta_Media = mean(REMUNERACAO_BRUTA), Rem_Liq_Media = mean(Remuneração.Após.Descontos.Obrigatórios))
kable(a)
```

Then it gives the error:

```{r}
processing file: camara.Rmd |.............
| 20% ordinary text without R code

|.......................... | 40% label: unnamed-chunk-1 |....................................... | 60% ordinary text without R code

|.................................................... | 80% label: kable

Quitting from lines 24-26 (camara.Rmd) Error in eval(expr, envir, enclos) : objeto 'Remuneração.Fixa' não encontrado Calls: ... filter -> filter_ -> filter_.tbl_df -> filter_impl -> .Call Execução interrompida

Translating -> Object 'Remuneração.Fixa' not found.
```
I would greatly appreciate some help with this.

**Comment by LucianoSP** [comment] 2015-07-03 15:11
I just noticed that an old markdown documento, which used to work, doesn´t work anynome. For some reason, R Markdown complains if I use any character with accent (â, á) in the code, even though the same code runs fine in Rstudio console. I haven´t changed anything. What can be wrong?

**Comment by yihui** [comment] 2015-07-06 02:29
Duplicate of https://github.com/rstudio/rmarkdown/issues/463

**Closed by yihui** 2015-07-06 02:29 UTC

**Comment by LucianoSP** [comment] 2015-07-06 14:10
I saved the RMD with encoding (UTF-8)... It gives me this error:

 ```{r}
> knit('Relatorio.Rmd', encoding = 'UTF-8')


processing file: Relatorio.Rmd
  |.................................................................| 100%
  ordinary text without R code


output file: Relatorio.md

[1] "Relatorio.md"
Warning message:
invalid input found on input connection 'Relatorio.Rmd' 
 ```

**Comment by Aleina** [comment] 2016-05-24 16:15
I had the exact same problem with the button knitr and function knit(). I used the function rmarkdown::render() instead and it worked perfectly.
