### ISSUE TITLE
knitr::opts_knit$set(root.dir = "../") being ignored

### ISSUE THREAD

**Issue by sillasgonzaga** [yihui/knitr#1575] opened 2018-07-16 17:23 UTC
I have no idea what is happening here.

![](https://i.imgur.com/RrgVZf6.png)

See that the last chunk shows that the root.dir command is being ignored. However, I have another file, saved in the same directory as this Rmd file and it runs with no problem.

Edit: It seems any try of changing knitr options is being ignored:

![](https://i.imgur.com/k1fDL8a.png)
 
```
sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Portuguese_Brazil.1252  LC_CTYPE=Portuguese_Brazil.1252    LC_MONETARY=Portuguese_Brazil.1252
[4] LC_NUMERIC=C                       LC_TIME=Portuguese_Brazil.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.5.1  backports_1.1.2 magrittr_1.5    rprojroot_1.3-2 htmltools_0.3.6 tools_3.5.1    
 [7] base64enc_0.1-3 yaml_2.1.19     Rcpp_0.12.17    rmarkdown_1.10  stringi_1.1.7   knitr_1.20     
[13] jsonlite_1.5    digest_0.6.15   stringr_1.3.1   evaluate_0.10.1
```

**Comment by sillasgonzaga** [comment] 2018-07-16 20:20
Ok, now I know [what's happening](https://stackoverflow.com/questions/41911487/html-notebook-ignores-global-chunk-options)

**Comment by yihui** [comment] 2018-07-16 22:10
Duplicate of https://github.com/rstudio/rmarkdown/issues/1077

**Closed by yihui** 2018-07-16 22:10 UTC
